// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Data$Covid_stats = require("./Data.bs.js");
var Page$Covid_stats = require("./Page.bs.js");

var monthNames = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec"
];

function byStateName(indexA, indexB) {
  var states = Data$Covid_stats.csv.states;
  var result = Caml_array.caml_array_get(states, indexA).name > Caml_array.caml_array_get(states, indexB).name ? 1 : (
      Caml_array.caml_array_get(states, indexA).name < Caml_array.caml_array_get(states, indexB).name ? -1 : 0
    );
  if (Page$Covid_stats.pageState.dir === /* Ascending */0) {
    return result;
  } else {
    return -result | 0;
  }
}

function byTotal(indexA, indexB) {
  var states = Data$Covid_stats.csv.states;
  var totalA = Page$Covid_stats.pageState.period === /* All */0 ? Caml_array.caml_array_get(states, indexA).totalCases : Caml_array.caml_array_get(states, indexA).pastWeekCases;
  var totalB = Page$Covid_stats.pageState.period === /* All */0 ? Caml_array.caml_array_get(states, indexB).totalCases : Caml_array.caml_array_get(states, indexB).pastWeekCases;
  var valueA = totalA / (
    Page$Covid_stats.pageState.col === /* Total */1 ? 1.0 : Caml_array.caml_array_get(states, indexA).population * 100000.0
  );
  var valueB = totalB / (
    Page$Covid_stats.pageState.col === /* Total */1 ? 1.0 : Caml_array.caml_array_get(states, indexB).population * 100000.0
  );
  var result = valueA > valueB || valueA >= valueB ? 1 : 0;
  if (Page$Covid_stats.pageState.dir === /* Ascending */0) {
    return result;
  } else {
    return -result | 0;
  }
}

console.log("About to fetch data");

function getPopulation(cases) {
  return fetch("covid_county_population_usafacts.csv").then(function (prim) {
                return prim.text();
              }).then(function (population) {
              return Promise.resolve((Data$Covid_stats.analyzeData(cases, population), Page$Covid_stats.drawTable(undefined)));
            });
}

function fetchData(param) {
  return fetch("covid_confirmed_usafacts.csv").then(function (prim) {
                return prim.text();
              }).then(function (cases) {
              return Promise.resolve(getPopulation(cases));
            });
}

exports.monthNames = monthNames;
exports.byStateName = byStateName;
exports.byTotal = byTotal;
exports.getPopulation = getPopulation;
exports.fetchData = fetchData;
/*  Not a pure module */
